### PR TITLE
Adding pivot class to event payload

### PR DESCRIPTION
**Pull request by MuriloChianfa**
hello man, i have use your package for try to implement a new feature in revisionable package, the many to many revisionable feature, and your package is necessary to this feature but with this alterations, can u accept this changes to we implement this new feature in the revisionable package?

the revisionable issue: [https://github.com/VentureCraft/revisionable/issues/63](https://github.com/VentureCraft/revisionable/issues/63)

i already managed to integrate the code with your package, we just need to update both

### CODE REVIEW

**Comment by MuriloChianfa** [comment]
i have tests the change on my fork and have all successed
image

**Comment by MuriloChianfa** [comment]
if you accept the changes i recomend to increment the minor version of packet for not broke the compatibility of fireModelEvent

**Comment by fico7489** [comment]
hey, can you fetch class just like that :
```

static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {
	$pivotClass = get_class($model->$relationName()->getRelated());
});
```

**Comment by MuriloChianfa** [comment]
ok its works fine. tnhx.

**Pull request closed without merging**
