### PR TITLE
Use indexed array for event payload

### PR DESCRIPTION
**Pull request by erikgaal**
We've discussed this PR before (#29) which had been rejected. However, the issue that this PR aims to solve is popping up in Laravel's Telescope too (laravel/telescope#187). Again, I would like to ask you to consider the PR as there are more users running into the issue with the event payload.

### CODE REVIEW

**Comment by fico7489** [comment]
actually this is not backward compatible, but I will include it in new 4.* version 
https://github.com/fico7489/laravel-pivot/tree/new

**Comment by Ben52** [comment]
This also affects those using https://github.com/GeneaLabs/laravel-model-caching together with Telescope

**Comment by denitsa-md** [comment]
Any idea when this will be released? Also having the problem with telescope and model caching.

**Comment by Ben52** [comment]
@denitsa-cm I resolved it like this https://github.com/laravel/telescope/issues/187#issuecomment-442486814

**Comment by ngunyimacharia** [comment]
Any progress on merging and releasing this? It's been 1yr+ since the pull request was created. Just experienced this issue today.

**Pull request merged**
