### PR TITLE
Added return false in the event handler to prevent changes

### PR DESCRIPTION
**Pull request by alexinfurs**
like Eloquent original events

### CODE REVIEW

**Comment by fico7489** [comment]
what is the purpose of this PR ? we are already returning what parent returns so the original behaviour is not changed..

**Comment by alexinfurs** [comment]
returning false in the event handler, no actual transaction will be performed. This adds the same feature we have in the original Eloquent's events

example

```php
static::pivotAttaching(function ($model, $relationName, $pivotIds, $pivotIdsAttributes) {

    if (someCondition) {
         return false; // pivot will not be attached
    }
   ...
}
```

**Comment by fico7489** [comment]
but originally 

    public function attach($id, array $attributes = [], $touch = true)

 in 

    Illuminate\Database\Eloquent\Relations\Concerns\InteractsWithPivotTable

is always performed with you code is not always, so you code changes original behaviour ...

**Comment by alexinfurs** [comment]
yes, but I'm just referring to the events behavior

According to the docs
> **Stopping The Propagation Of An Event**
Sometimes, you may wish to stop the propagation of an event to other listeners. You may do so by returning **false** from your listener's **handle** method.

```php
self::creating(function($model) {
     return false; // model will not be created
});

self::updating(function($model) {
     return false; // model will not be updated
});
```
...and so on

I'd like just to add the same option in the pivot attaching/detaching event

**Pull request closed without merging**
