### PR TITLE
Update dependencies for Laravel 10

### PR DESCRIPTION
**Pull request by cheesegrits**
Passes tests.

### CODE REVIEW

**Comment by fico7489** [comment]
hey,

can you add 10.* here: https://github.com/fico7489/laravel-pivot/blob/master/.github/workflows/test.yml#L15

**Comment by cheesegrits** [comment]
> hey,
> 
> can you add 10.* here: https://github.com/fico7489/laravel-pivot/blob/master/.github/workflows/test.yml#L15

Done

**Comment by Treggats** [comment]
@fico7489 currently tests are failing due to outdated PHPUnit configuration. I've created #89 to fix.

**Comment by Treggats** [comment]
@cheesegrits can you update your fork with the target branch? It contains a PHPUnit config changes that lets tests for this PR pass.

**Pull request merged**
