### PR TITLE
Update BelongsToManyCustom.php

### PR DESCRIPTION
**Pull request by lewisf2001uk**
Minor change to fix Laravel's attach method, we may need to add test for this later.

### CODE REVIEW

**Comment by fico7489** [comment]
@lewisf2001uk  actually I chaged 
 
`parent::attach($ids, [], $touch);`

to

`parent::attach($idsAttributes, [], $touch);`

All attributes are already calculated in $idsAttributes so second argument can be an empty array. Take a look at my last commits, I fixed this and cover with tests.

**Comment by lewisf2001uk** [comment]
Ah sorry I didn't have an environment to run the tests where I was.
Just as a point for discussion, wouldn't it be better to pass the variables to the parent (Laravel Framework) function as you get them (when overriding the function). This way if anything was to change in future with how the attach method works in the Laravel framework (using the same variables), you package wouldn't make it cause issues?
Doing it this way would all have it work in a similar way to how your other overridden functions work.

**Comment by fico7489** [comment]
@lewisf2001uk  yes, you are right, I should pass to the parent what I get here, this also came to my mind yesterday. 

Cons for passing to parent what you get here are : 
- double calculation for array (in package and parent)
- a package will anyway not work as aspected if something changes in the parent, or if something works differently in the parent
- if parent function calculates this array differently than our function user will get the event with wrong data in $pivotIdsAttributes variable


although now everything works as expected(for int, array, array with attributes, model, and collection) and tests are passing I will pass to the parent what I get here anyway...

When I think a little bit I am don't know if we should calculate $pivotIdsAttributes variable or we should just pass to the event what is received (raw data)...

**Comment by lewisf2001uk** [comment]
@fico7489 I understand what you are saying in regards to the cons, however I always feel funny about changing how data is passed to the Framework as sometimes something unexpected could arise.

In regards to calculating the $pivotIdsAttributes, again I can understand what you are saying, however we will need to run some sort of function like "getIdsWithAttributes" to get the pivot ids. It depends on if you want to make a breaking change and just pass to the event the $id / $attributes received from the attach method, and provide a trait or similar to help the users get the information they require out of these variables.

**Comment by fico7489** [comment]
@lewisf2001uk  you are 100% right, I changed this 
https://github.com/fico7489/laravel-pivot/commit/5e0b2192774082fad252e2709ce8b3171ef8b91d

**Pull request closed without merging**
